[workspace]
members = [
    "additional-nodes",
    "editor-backend",
    "musicbx",
    "musicbx/musicbx-codegen",
    "musicbx/musicbx-core",
    "musicbx/musicbx-derive",
    "musicbx/musicbx-std",
    "musicbx/musicbx-types",
]

[profile.release]
lto = true

