[workspace]
members = [
    "editor-backend",
    "musicbx",
    "musicbx-codegen",
    "musicbx-core",
    "musicbx-extra",
    "musicbx-derive",
    "musicbx-std",
    "musicbx-types",
    "additional-nodes",
]

[profile.release]
lto = true

