[package]
edition = "2021"
name = "musicbx-codegen"
version = "0.1.0"

[dependencies]
itertools = "0.10.3"
musicbx-types = { path = "../musicbx-types" }
proc-macro2 = "1.0.39"
quote = "1.0.18"
serde_json = "1.0.81"
syn = "1.0.95"
thiserror = "1.0.31"
