[package]
name = "musicbx-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
musicbx-core = { path = "../musicbx-core" }
musicbx-macro = { path = "../musicbx-macro" }
rand = "0.8.5"
